[project]
name = "nba"
version = "0.1.0"
description = "NBA project"
requires-python = ">=3.8"
dependencies = [
    "nba-api>=1.5.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."] 
